baseurl = "https://hloh42.github.io/"
publishDir = "public"
contentDir = "content"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5
relativeURLs = false
canonifyURLS = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  gtm_id = "GTM-T99GWB69"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "hloh42 Journey"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
